services:
  - type: web
    name: python-challenge-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
